# Generated by Django 2.1.1 on 2019-09-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('plazas', models.IntegerField()),
                ('tipo_pizarra', models.CharField(choices=[(1, 'pizarra verde'), (2, 'pizarra blanca')], default=1, max_length=1)),
                ('tipo_aula', models.CharField(choices=[(1, 'pupitres'), (2, 'mesa compartida'), (3, 'mesa dibujo'), (4, 'solo silla')], default=1, max_length=1)),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bedel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.Aula')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.Docente')),
            ],
        ),
    ]
