# Generated by Django 2.1.1 on 2019-09-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='tipo_aula',
            field=models.CharField(choices=[('1', 'pupitres'), ('2', 'mesa compartida'), ('3', 'mesa dibujo'), ('4', 'solo silla')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='aula',
            name='tipo_pizarra',
            field=models.CharField(choices=[('1', 'pizarra verde'), ('2', 'pizarra blanca')], default=1, max_length=1),
        ),
    ]
